### ISSUE TITLE
no main manifest attribute, in vocabLite-1.0.jar

### ISSUE THREAD

**Issue by chunhualiao** [dgarijo/vocabLite#10]
I downloaded the jar file from https://github.com/dgarijo/vocabLite/tree/master/target

I am getting the following error:
 
java -jar third-party-tools/vocabLite-1.0.jar -i development -o release -n HPC-Ontology
 
no main manifest attribute, in third-party-tools/vocabLite-1.0.jar

**Comment by dgarijo** [comment]
Have you tried with the jar in releases?
https://github.com/dgarijo/vocabLite/releases/tag/1.0.2

It's the one that should be used. I have not maintained this repo in a
while, I will try and double check the jar is correct

**Comment by chunhualiao** [comment]
It works now. There are some ttl files which could not be loaded. I will look into them (mostly my own fault).

**Comment by dgarijo** [comment]
Nice!, please close the issue if it's solved :)
